[build]
  command = "npm run build"
  publish = "dist"
  
  # Specify a Node version that matches your project requirements
  [build.environment]
    NODE_VERSION = "16"
    NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate" 